//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Özkader_Otomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Iletisim
    {
        public int IletisimID { get; set; }
        public string IletisimAd { get; set; }
        public string IletisimTelefon { get; set; }
        public string IletisimFirma { get; set; }
        public string IletisimEposta { get; set; }
        public string IletisimAdres { get; set; }
        public string IletisimMesaj { get; set; }
    }
}
