//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Özkader_Otomotiv.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urun
    {
        public int UrunID { get; set; }
        public Nullable<int> UrunKategori { get; set; }
        public string UrunAd { get; set; }
        public string UrunVolt { get; set; }
        public string UrunYedekParca1 { get; set; }
        public string UrunYedekParca2 { get; set; }
        public string UrunYedekParca3 { get; set; }
        public string UrunYedekParca4 { get; set; }
        public string UrunYedekParca5 { get; set; }
        public string UrunYedekParca6 { get; set; }
        public string UrunKullanilanAraclar1 { get; set; }
        public string UrunKullanilanAraclar2 { get; set; }
        public string UrunKullanilanAraclar3 { get; set; }
        public string UrunKullanilanAraclar4 { get; set; }
        public string UrunKullanilanAraclar5 { get; set; }
        public string UrunOemNo1 { get; set; }
        public string UrunOemNo2 { get; set; }
        public string UrunFotograf { get; set; }
    
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
    }
}
